services:
  - type: worker
    name: crime-consumer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python consumer1.py"
    envVars:
      - key: BOOTSTRAP_SERVERS
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false

  - type: worker
    name: sf-gov-producer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python sf_api_producer.py"
    envVars:
      - key: BOOTSTRAP_SERVERS
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false

- type: web
  name: route-dashboard
  env: python
  plan: free
  buildCommand: "pip install -r requirements.txt"
  startCommand: "streamlit run app1.py --server.port=10000 --server.address=0.0.0.0"
  envVars:
    - key: ORS_API_KEY
      sync: false
