services:
  - type: worker
    name: crime-consumer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python consumer1.py"
    envVars:
      - key: BOOTSTRAP_SERVERS
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false